language: node_js

node_js: stable

cache:
  yarn: true
  direactories:
    - node_modules

install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $DEPLOY_TOKEN
  local-dir: dist
  on:
    branch: master
