version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Unit test
          command: yarn test

      - run:
          name: Test generating process
          command: |
            if [ $CIRCLE_BRANCH != $SOURCE_BRANCH ]; then
              yarn build
            fi

      - add_ssh_keys:
          fingerprints:
            - '34:b5:fb:2b:52:ce:50:d6:71:8f:d3:26:cf:de:9b:70'

      - deploy:
          name: Deploy site
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $USER_MAIL
              git config --global user.name $USER_NAME

              yarn build
              mkdir -p dist/.circleci
              cp -a .circleci/. dist/.circleci/.
              cd dist

              git init
              git add .
              git commit -m "Site: Deployed by CircleCI - ${CIRCLE_SHA1}" --allow-empty

              git push -f git@github.com:lbwa/adminize.git master:gh-pages
            fi
